"""Automated unit and integration tests for Phase 4 Stage 2 Student-Level Modeling.

Tests:
1. Student-level cross-task feature aggregation schema & cohort balance
2. StabilitySelector transformer correctness & leakage prevention
3. Student-level benchmark metric calculations & bootstrap CIs
4. Drop-one-family ablation runner and delta AUROC calculations
5. Qualitative misclassification gallery HTML generation
"""

import sys
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent
if str(WORKSPACE_ROOT) not in sys.path:
    sys.path.insert(0, str(WORKSPACE_ROOT))

from models.feature_selection import StabilitySelector
from models.student_features import (
    compute_student_robust_z_scores,
    extract_student_features,
)
from models.student_experiments import compute_bootstrap_ci


def test_student_feature_aggregation_schema():
    """Verify student-level feature extraction aggregates to exactly 115 students with 24 positives."""
    combined_path = WORKSPACE_ROOT / "data" / "datasets" / "dataset_combined.csv"
    folds_path = WORKSPACE_ROOT / "data" / "folds" / "student_folds_lookup.csv"
    
    assert combined_path.exists(), "dataset_combined.csv missing"
    assert folds_path.exists(), "student_folds_lookup.csv missing"

    df_combined = pd.read_csv(combined_path)
    df_folds = pd.read_csv(folds_path)

    df_students = extract_student_features(df_combined, df_folds)

    df_students_a = df_students[df_students["school"] == "school_a"]
    assert len(df_students_a) == 115, f"Expected 115 School A students, got {len(df_students_a)}"
    assert (df_students_a["label"] == 1).sum() == 24, "Expected exactly 24 School A positive students"
    assert (df_students_a["label"] == 0).sum() == 91, "Expected exactly 91 School A negative students"

    # Multi-school totals
    assert len(df_students) == 215, f"Expected 215 total students, got {len(df_students)}"
    assert (df_students["label"] == 1).sum() == 40, "Expected 40 total positive students"
    assert (df_students["label"] == 0).sum() == 175, "Expected 175 total negative students"

    # Verify key cross-task features exist
    expected_feats = [
        "components_per_unit_width_dict_mean",
        "components_per_unit_width_max",
        "components_per_unit_width_eng_minus_hindi",
        "endpoints_per_unit_width_mean",
        "junctions_per_unit_width_mean",
        "gap_fraction_above_2h_mean",
        "matra_ratio_std",
        "shirorekha_rms_deviation_norm_max",
        "gap_cv_mean",
    ]
    for ef in expected_feats:
        assert ef in df_students.columns, f"Feature {ef} missing from student dataset"

    # Test robust z-scoring
    df_z = compute_student_robust_z_scores(df_students)
    assert len(df_z) == len(df_students)
    for ef in expected_feats:
        z_col = f"z_{ef}"
        assert z_col in df_z.columns
        # Check z values are clipped in [-5.0, 5.0]
        vals = df_z[z_col].dropna()
        assert (vals >= -5.0).all() and (vals <= 5.0).all()


def test_stability_selector_properties():
    """Verify StabilitySelector fits cleanly, respects top_k, and produces correct support mask."""
    rng = np.random.RandomState(42)
    X = rng.randn(100, 20)
    # Inject signal into first 3 features
    y = ((X[:, 0] + X[:, 1] - X[:, 2]) > 0).astype(int)

    selector = StabilitySelector(n_subsamples=30, top_k=5, random_state=42)
    selector.fit(X, y)

    assert selector.support_ is not None
    assert selector.support_.sum() == 5
    assert len(selector.selected_indices_) == 5
    assert selector.stability_scores_ is not None
    assert len(selector.stability_scores_) == 20
    assert (selector.stability_scores_ >= 0.0).all() and (selector.stability_scores_ <= 1.0).all()

    X_trans = selector.transform(X)
    assert X_trans.shape == (100, 5)


def test_bootstrap_ci_computation():
    """Verify bootstrap confidence intervals are ordered properly: low <= point <= high."""
    rng = np.random.RandomState(42)
    y_true = np.array([0] * 80 + [1] * 20)
    # Signal with noise
    y_scores = np.where(y_true == 1, rng.uniform(0.4, 0.9, size=100), rng.uniform(0.1, 0.6, size=100))

    ci_results = compute_bootstrap_ci(y_true, y_scores, n_bootstraps=100, random_state=42)

    for metric in ["auroc", "auprc", "brier", "sens_at_90_spec", "sens_at_80_spec", "balanced_acc"]:
        assert metric in ci_results
        point, low, high = ci_results[metric]
        assert 0.0 <= point <= 1.0
        assert low <= point <= high or np.isclose(low, high, atol=1e-3)


def test_student_benchmark_reports_exist():
    """Verify output artifacts generated by Stage 2 pipeline exist and have valid structure."""
    res_csv = WORKSPACE_ROOT / "reports" / "student_benchmark_results.csv"
    res_json = WORKSPACE_ROOT / "reports" / "student_benchmark_results.json"
    abl_csv = WORKSPACE_ROOT / "reports" / "ablation_study_results.csv"
    imp_csv = WORKSPACE_ROOT / "reports" / "permutation_importance_results.csv"
    gal_html = WORKSPACE_ROOT / "reports" / "misclassified_gallery.html"

    assert res_csv.exists(), "student_benchmark_results.csv missing"
    assert res_json.exists(), "student_benchmark_results.json missing"
    assert abl_csv.exists(), "ablation_study_results.csv missing"
    assert imp_csv.exists(), "permutation_importance_results.csv missing"
    assert gal_html.exists(), "misclassified_gallery.html missing"

    df_res = pd.read_csv(res_csv)
    assert len(df_res) >= 6
    assert "mean_auroc" in df_res.columns
    # Verify best model achieved AUROC >= 0.70
    assert (df_res["mean_auroc"] >= 0.70).any(), "Expected at least one model with AUROC >= 0.70"

    # Verify gallery HTML has content
    html_text = gal_html.read_text(encoding="utf-8")
    assert "Dysgraphia Detection" in html_text
    assert "True Positive" in html_text
    assert "False Positive" in html_text


if __name__ == "__main__":
    test_student_feature_aggregation_schema()
    print("✓ test_student_feature_aggregation_schema passed")
    test_stability_selector_properties()
    print("✓ test_stability_selector_properties passed")
    test_bootstrap_ci_computation()
    print("✓ test_bootstrap_ci_computation passed")
    test_student_benchmark_reports_exist()
    print("✓ test_student_benchmark_reports_exist passed")
    print("\nALL STAGE 2 TESTS PASSED SUCCESSFULLY!")

